@ArtemisBank.WebAPI_HostAddress = http://localhost:7073

POST {{ArtemisBank.WebAPI_HostAddress}}/api/v1/Users

{
  "firstName": "prueba",
  "lastName": "ana",
  "cedula": "00022558833",
  "email": "user@example.com",
  "userName": "example",
  "password": "Example123!",
  "confirmPassword": "Example123",
  "role": "2",
  "initialAmount": 1000
}